version: '3'
services:
  go-ethereum:
    image: ethereum/client-go:release-1.13
    volumes:
      - ./go-ethereum/genesis.json:/tmp/genesis.json
    entrypoint: >
        sh -c "geth --datadir /ethereum --networkid 1234 init /tmp/genesis.json && geth --dev --datadir /ethereum --networkid 1234 --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,debug,personal,txpool --allow-insecure-unlock --nodiscover --ipcdisable --nat extip:127.0.0.1"
    ports:
      - "8545:8545"
