version: "3"

services:
  # https://book.getfoundry.sh/reference/anvil
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-3df3e0c0d72dedcba3ea57afd2f57ebd231624dd
    entrypoint: |
      anvil
        --host 0.0.0.0
        --port 8545
        --init /genesis.json
        --optimism
        --no-mining
        --disable-block-gas-limit
    ports:
      - "8545:8545"
    volumes:
      - ./anvil/genesis.json:/genesis.json

